/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef autotrade_CONSTANTS_H
#define autotrade_CONSTANTS_H

#include "autotrade_types.h"

namespace com { namespace autotrade { namespace zxtradesdk {

class autotradeConstants {
 public:
  autotradeConstants();

};

extern const autotradeConstants g_autotrade_constants;

}}} // namespace

#endif
