/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "autotrade_constants.h"

namespace com { namespace autotrade { namespace zxtradesdk {

const autotradeConstants g_autotrade_constants;

autotradeConstants::autotradeConstants() {
}

}}} // namespace

